export default {
    FACE_NEUTRAL: 0,

    FACE_HAPPY: 1,
    FACE_CHEERFUL: 2,
    FACE_LAUGHING: 3,

    FACE_BORED: 4,
    FACE_ANNOYED: 5,
    FACE_ANGRY: 6,

    FACE_MERRY: 7,
    FACE_DRUNK: 8,
    FACE_HAMMERED: 9,

    FACE_GOURMAND: 10,
    FACE_GLUTTONOUS: 11,
    FACE_SICK: 12,
};
